import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


SENDER_EMAIL = "sender_mail"
SENDER_PASSWORD = "Extract_app_password"  # Gmail App Password


def send_evaluation_email(
    receiver_email,
    plant,
    status,
    severity,
    confidence,
    summary,
    care,
    prevention,
    disease_name=None,
    affected_area=None
):
    try:
        subject = "🌱 Smart Plant Doctor - Evaluation Report"

        # Base Report
        body = f"""
SMART PLANT DISEASE EVALUATION REPORT

Plant Detected: {plant}
Status: {status}
Severity Level: {severity}
Confidence: {confidence}%
"""

        # Add Disease Details (Only if Diseased)
        if disease_name:
            body += f"""
Disease Name: {disease_name}
Area Affected: {affected_area}%
"""

        # Always Add These Sections
        body += f"""

Summary:
{summary}

Care Tips:
{care}

Prevention:
{prevention}

Generated by Intelligent Plant Disease Diagnosis System.
"""

        # Create Email
        msg = MIMEMultipart()
        msg["From"] = SENDER_EMAIL
        msg["To"] = receiver_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        # Connect to Gmail SMTP
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()

        print("✅ Email sent successfully!")
        return True

    except Exception as e:
        print("❌ Email Error:", str(e))
        return False